from data_loaders.base_raganato_data_loader import BaseRaganatoDataLoader, TrainWord
from data_loaders.semcor_data_loader import SemcorDataLoader
from data_loaders.semeval_dataloader import SemevalDataLoader
